version: '3'
services:
  php:
    build: .
    volumes:
      - ~/Dropbox/blog_text_compression:/var/www/html
    hostname: sample-web
    ports:
      - '8080:80'
    networks:
      - sample-network

networks:
    sample-network:
        name: sample-network
        external: true
